fixes

diff --git a/codeql-local/db/db-javascript/default/pools/0/pageDump/page-000000000 b/codeql-local/db/db-javascript/default/pools/0/pageDump/page-000000000
--- a/codeql-local/db/db-javascript/default/pools/0/pageDump/page-000000000
+++ b/codeql-local/db/db-javascript/default/pools/0/pageDump/page-000000000
@@ -72,14 +72,14 @@ if [ "$TOTAL" -gt 0 ]; then
   echo "| Severity | Rule | Location | Message |" >> $GITHUB_STEP_SUMMARY
   echo "| --- | --- | --- | --- |" >> $GITHUB_STEP_SUMMARY
   
-  # Process all SARIF files to extract comprehensive issue details
+  # Process all SARIF files to extract comprehensive issue details with safer jq formatting
   find sarif-results -name "*.sarif" -type f | while read -r file; do
     jq -r '.runs[0].results[] | 
       "| " + (.properties.severity // "unknown") + 
       " | " + (.rule.id // .ruleId // "unnamed-rule") + 
       " | " + (.locations[0].physicalLocation.artifactLocation.uri // "unknown") + ":" + 
-        (.locations[0].physicalLocation.region.startLine // "0") + 
-      " | " + (.message.text // "No message provided") + " |"' "$file" >> $GITHUB_STEP_SUMMARY
+        (if .locations[0].physicalLocation.region.startLine then (.locations[0].physicalLocation.region.startLine | tostring) else "0" end) + 
+      " | " + (.message.text // "No message provided") + " |"' "$file" || echo "Error processing $file" >> $GITHUB_STEP_SUMMARY
   done
 else
   echo "ðŸŽ‰ **No security issues found!**" >> $GITHUB_STEP_SUMMARY
@@ -13273,4 +13273,4 @@ should be removed.Set of possible string values: 'error', 'loaded', 'loading', '
 http://dev.w3.org/csswg/css-font-loading/#dom-fontfaceset-clear
 http://dev.w3.org/csswg/css-font-loading/#dom-fontfaceset-delete
 http://dev.w3.org/csswg/css-font-loading/#dom-fontfaceset-hasfunction (!FontFace, number, !FontFaceSet)see http://dev.w3.org/csswg/css-font-loading/#dom-fontfaceset-foreach
-(Object|undefined)=!Promise.<!Array.<!FontFace>>Promise.<!Array.<!FontFace>>!Array.<!FontFace>Array.<!FontFace>http://dev.w3.org/csswg/css-font-loading/#dom-fontfaceset-loadhttp://dev.w3.org/csswg/css-font-loading/#dom-fontfaceset-check!Promise.<!FontFaceSet>Promise.<!FontFaceSet>http://dev.w3.org/csswg/css-font-loading/#dom-fontfaceset-readyhttp://dev.w3.org/csswg/css-font-loading/#dom-fontfaceset-statusStyleSh ... e.type;StyleSh ... pe.typeStyleSh ... sabled;StyleSh ... isabledStyleSh ... erNode;StyleSh ... nerNodeStyleSh ... eSheet;StyleSh ... leSheetStyleSh ... e.href;StyleSh ... pe.hrefStyleSh ... .title;StyleSh ... e.titleStyleSh ... .media;StyleSh ... e.mediaStyleSh ... length;StyleSh ... .lengthStyleSh ... ototypeStyleSh ... ex) {};StyleSh ... dex) {}StyleSh ... pe.itemMediaLi ... iaText;MediaLi ... diaTextMediaList.prototypeMediaLi ... length;MediaLi ... .lengthMediaLi ... ex) {};MediaLi ... dex) {}MediaLi ... pe.itemLinkSty ... .sheet;LinkSty ... e.sheetLinkStyle.prototypeDocumen ... ototypeCSSStyl ... erRule;CSSStyl ... nerRuleCSSStyl ... ototypeCSSStyl ... sRules;CSSStyl ... ssRulesCSSStyl ... ex) {};CSSStyl ... dex) {}CSSStyl ... ertRuleCSSStyl ... eteRuleCSSRule ... length;CSSRule ... .lengthCSSRule ... ototypeCSSRule ... ex) {};CSSRule ... dex) {}CSSRule ... pe.itemCSSRule ... e.type;CSSRule ... pe.typeCSSRule.prototypeCSSRule ... ssText;CSSRule ... cssTextCSSRule ... eSheet;CSSRule ... leSheetCSSRule ... ntRule;CSSRule ... entRuleCSSRule ... .style;CSSRule ... e.styleCSSRule ... LE = 0;CSSRule ... ULE = 0CSSRule.UNKNOWN_RULECSSRule ... LE = 1;CSSRule ... ULE = 1CSSRule.STYLE_RULECSþÿ ÷  æ¹Çl    
+(Object|undefined)=!Promise.<!Array.<!FontFace>>Promise.<!Array.<!FontFace>>!Array.<!FontFace>Array.<!FontFace>http://dev.w3.org/csswg/css-font-loading/#dom-fontfaceset-loadhttp://dev.w3.org/csswg/css-font-loading/#dom-fontfaceset-check!Promise.<!FontFaceSet>Promise.<!FontFaceSet>http://dev.w3.org/csswg/css-font-loading/#dom-fontfaceset-readyhttp://dev.w3.org/csswg/css-font-loading/#dom-fontfaceset-statusStyleSh ... e.type;StyleSh ... pe.typeStyleSh ... sabled;StyleSh ... isabledStyleSh ... erNode;StyleSh ... nerNodeStyleSh ... eSheet;StyleSh ... leSheetStyleSh ... e.href;StyleSh ... pe.hrefStyleSh ... .title;StyleSh ... e.titleStyleSh ... .media;StyleSh ... e.mediaStyleSh ... length;StyleSh ... .lengthStyleSh ... ototypeStyleSh ... ex) {};StyleSh ... dex) {}StyleSh ... pe.itemMediaLi ... iaText;MediaLi ... diaTextMediaList.prototypeMediaLi ... length;MediaLi ... .lengthMediaLi ... ex) {};MediaLi ... dex) {}MediaLi ... pe.itemLinkSty ... .sheet;LinkSty ... e.sheetLinkStyle.prototypeDocumen ... ototypeCSSStyl ... erRule;CSSStyl ... nerRuleCSSStyl ... ototypeCSSStyl ... sRules;CSSStyl ... ssRulesCSSStyl ... ex) {};CSSStyl ... dex) {}CSSStyl ... ertRuleCSSStyl ... eteRuleCSSRule ... length;CSSRule ... .lengthCSSRule ... ototypeCSSRule ... ex) {};CSSRule ... dex) {}CSSRule ... pe.itemCSSRule ... e.type;CSSRule ... pe.typeCSSRule.prototypeCSSRule ... ssText;CSSRule ... cssTextCSSRule ... eSheet;CSSRule ... leSheetCSSRule ... ntRule;CSSRule ... entRuleCSSRule ... .style;CSþÿ ÷  Óc"ü    
