character length

diff --git a/codeql-local/db/db-javascript/default/pools/0/pageDump/page-000000000 b/codeql-local/db/db-javascript/default/pools/0/pageDump/page-000000000
--- a/codeql-local/db/db-javascript/default/pools/0/pageDump/page-000000000
+++ b/codeql-local/db/db-javascript/default/pools/0/pageDump/page-000000000
@@ -176,7 +176,47 @@ touch docs/.nojekyll
 name: C ... rectoryUpload artifactactions/upload-pages-artifact@v1actions ... fact@v1docspath: docs- name: Checkoutruns-on ... -latestdeployenvironmentgithub-pagesurl${{ steps.deployment.outputs.page_url }}${{ ste ... _url }}name: github-pagesneedsdeploymentactions/deploy-pages@v2actions ... ages@v2name: D ... b Pages- name: ... b Pagesenvironment:build:/Users/vishruthvs/Projects/aem-guides-wknd/.github/workflows/deploy-to-wknd-prod.ymlDeploy to WKND.site ProductionDeploy  ... ductionenvTARGET_REPO${{ secrets.WKND_REPOSITORY }}${{ sec ... TORY }}TARGET_BRANCH_DEV${{ secrets.WKND_BRANCH_DEV }}${{ sec ... _DEV }}TARGET_BRANCH_PROD${{ secrets.WKND_BRANCH_PROD }}${{ sec ... PROD }}USER_EMAIL${{ secrets.WKND_USER_EMAIL }}${{ sec ... MAIL }}USER_NAME${{ secrets.WKND_USER_NAME }}${{ sec ... NAME }}USER_PWD${{ secrets.WKND_PASSWORD }}${{ sec ... WORD }}TARGET_ ... TORY }}master[ master ]branches: [ master ]fetch-depth'0'fetch-depth: '0'uses: a ... kout@v4Add WKND remotegit remote add wknd https://${USER_EMAIL}:${USER_PWD}@${TARGET_REPO}git rem ... T_REPO}name: A ...  remoteSet Git configgit config --global credential.helper cache
 git config --global user.email ${USER_EMAIL}
 git config --global user.name ${USER_NAME}
-name: Set Git configPush changes to WKND DevelopmentPush ch ... lopmentgit push -u wknd master:${TARGET_BRANCH_DEV}git pus ... CH_DEV}name: P ... lopmentPush changes to WKND ProductionPush ch ... ductiongit push -u wknd master:${TARGET_BRANCH_PROD}git pus ... H_PROD}name: P ... duction- uses: ... kout@v4name: D ... duction/Users/vishruthvs/Projects/aem-guides-wknd/.github/workflows/maven-release.ymlRelease to OSSRHinputsreleaseVersionRelease version (major.minor.patch)'Releas ... patch)'required''descrip ... patch)'dryRunDry Run? (false to do an actual release)'Dry Ru ... lease)''true'descrip ... lease)'releaseVersion:inputs:workflow_dispatch:releasegithub.repository == 'adobe/aem-guides-wknd' && github.ref == 'refs/heads/main'github. ... s/main'actions/checkout@v3uses: a ... kout@v3Setup JDKactions/setup-java@v3actions ... java@v3distributiontemurin'temurin'java-versionmavendistrib ... emurin'name: Setup JDKImport GPG keyGPG_SECRET_KEYS${{ secrets.GPG_SECRET_KEYS }}${{ sec ... KEYS }}GPG_OWNERTRUST${{ secrets.GPG_OWNERTRUST }}${{ sec ... RUST }}GPG_SEC ... KEYS }}echo $GPG_SECRET_KEYS | base64 --decode | gpg --import --no-tty --batch --yes
+name: Set Git configPush changes to WKND DevelopmentPush ch ... lopmentgit push -u wknd master:${TARGET_BRANCH_DEV}git pus ... CH_DEV}name: P ... lopmentPush changes to WKND ProductionPush ch ... ductiongit push -u wknd master:${TARGET_BRANCH_PROD}git pus ... H_PROD}name: P ... duction- uses: ... kout@v4name: D ... duction/Users/vishruthvs/Projects/aem-guides-wknd/.github/workflows/line-length-check.ymlLine Length Check"Line Length Check"pathsui.frontend/**'ui.frontend/**'- 'ui.frontend/**'check-line-lengthCheck Line LengthCheck for lines exceeding 120 charactersCheck f ... ractersecho "# Line Length Check Results" >> $GITHUB_STEP_SUMMARY
+echo "" >> $GITHUB_STEP_SUMMARY
+
+# Find files with lines exceeding 120 characters in ui.frontend directory
+LONG_LINES=$(grep -r --include="*.*" -n ".\{121,\}" ui.frontend || true)
+
+if [ -z "$LONG_LINES" ]; then
+  echo "âœ… No lines exceeding 120 characters found in ui.frontend directory." >> $GITHUB_STEP_SUMMARY
+  echo "::notice::No lines exceeding 120 characters found."
+else
+  # Count total violations
+  LINE_COUNT=$(echo "$LONG_LINES" | wc -l)
+  echo "âŒ Found $LINE_COUNT lines exceeding 120 characters in ui.frontend directory:" >> $GITHUB_STEP_SUMMARY
+  echo "" >> $GITHUB_STEP_SUMMARY
+  
+  # Create a table for the results
+  echo "| File | Line | Content |" >> $GITHUB_STEP_SUMMARY
+  echo "| ---- | ---- | ------- |" >> $GITHUB_STEP_SUMMARY
+  
+  # Process each line and add to the summary
+  echo "$LONG_LINES" | while IFS=':' read -r file line content; do
+    # Truncate content if too long for display
+    if [ ${#content} -gt 100 ]; then
+      display_content="${content:0:97}..."
+    else
+      display_content="$content"
+    fi
+    
+    # Escape content for markdown table
+    display_content=$(echo "$display_content" | sed 's/|/\\|/g')
+    
+    echo "| $file | $line | $display_content |" >> $GITHUB_STEP_SUMMARY
+    
+    # Create annotations visible in GitHub UI
+    echo "::warning file=$file,line=$line::Line exceeds 120 characters"
+  done
+  
+  # Make the check fail if we found any violations
+  echo "::error::Found $LINE_COUNT lines exceeding 120 characters in ui.frontend directory. See job summary for details."
+  exit 1
+finame: C ... ractersname: C ...  Lengthcheck-line-length:name: " ...  Check"/Users/vishruthvs/Projects/aem-guides-wknd/.github/workflows/maven-release.ymlRelease to OSSRHinputsreleaseVersionRelease version (major.minor.patch)'Releas ... patch)'required''descrip ... patch)'dryRunDry Run? (false to do an actual release)'Dry Ru ... lease)''true'descrip ... lease)'releaseVersion:inputs:workflow_dispatch:releasegithub.repository == 'adobe/aem-guides-wknd' && github.ref == 'refs/heads/main'github. ... s/main'actions/checkout@v3uses: a ... kout@v3Setup JDKactions/setup-java@v3actions ... java@v3distributiontemurin'temurin'java-versionmavendistrib ... emurin'name: Setup JDKImport GPG keyGPG_SECRET_KEYS${{ secrets.GPG_SECRET_KEYS }}${{ sec ... KEYS }}GPG_OWNERTRUST${{ secrets.GPG_OWNERTRUST }}${{ sec ... RUST }}GPG_SEC ... KEYS }}echo $GPG_SECRET_KEYS | base64 --decode | gpg --import --no-tty --batch --yes
 echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust --no-tty --batch --yes
 name: Import GPG keyConfigure git user for release commitsConfigu ... commitsX_GITHUB_USERNAME${{ secrets.ADOBE_BOT_GITHUB_USERNAME  }}${{ sec ... AME  }}X_GITHU ... AME  }}git config user.email "Grp-opensourceoffice@adobe.com"
 git config user.name "${X_GITHUB_USERNAME}"
@@ -6331,7 +6371,7 @@ assert.eql = eql;assert.eql = eqlassert.eql/opt/codeql/javascript/tools/data/ext
  * @param {string} path
  * @param {(function(boolean): *)} callback
  * @return {boolean}
- ParsedPathextpathspathSegmentsisAbsoluterelativedirnamebasenameextnamesepdelimiterpathStringpathObjectposixpPwin32_makeLongDefinitions for module "path"...stringpath.ParsedPath(function (boolean): *)function (boolean): *var path = {};path = {}path.Pa ... n() {};path.Pa ... on() {}path.Pa ... e.root;path.Pa ... pe.rootpath.Pa ... ototypepath.Pa ... pe.dir;path.Pa ... ype.dirpath.Pa ... e.base;path.Pa ... pe.basepath.Pa ... pe.ext;path.Pa ... ype.extpath.Pa ... e.name;path.Pa ... pe.namepath.no ... (p) {};path.no ... n(p) {}path.normalizefunction(p) {}path.jo ... hs) {};path.jo ... ths) {}function(paths) {}path.re ... ts) {};path.re ... nts) {}path.is ... th) {};path.is ... ath) {}path.isAbsolutepath.re ... to) {};path.re ...  to) {}path.relativefunctio ...  to) {}path.di ... (p) {};path.di ... n(p) {}path.dirnamepath.ba ... xt) {};path.ba ... ext) {}path.basenamefunction(p, ext) {}path.ex ... (p) {};path.ex ... n(p) {}path.extnamepath.sep;path.seppath.delimiter;path.delimiterpath.pa ... ng) {};path.pa ... ing) {}path.parsepath.fo ... ct) {};path.fo ... ect) {}path.formatfunctio ... ect) {}path.po ...  || {};path.po ... x || {}path.posixpath.posix || {}path.po ... (p) {};path.po ... n(p) {}path.posix.normalizepath.po ... hs) {};path.po ... ths) {}path.posix.joinpath.po ... ts) {};path.po ... nts) {}path.posix.resolvepath.po ... bsolutepath.po ... to) {};path.po ...  to) {}path.posix.relativepath.posix.dirnamepath.po ... xt) {};path.po ... ext) {}path.posix.basenamepath.posix.extnamepath.posix.sep;path.posix.seppath.po ... imiter;path.posix.delimiterpath.posix.parsepath.po ... pP) {};path.po ... (pP) {}path.posix.formatfunction(pP) {}path.wi ...  || {};path.wi ... 2 || {}path.win32path.win32 || {}path.wi ... (p) {};path.wi ... n(p) {}path.win32.normalizepath.wi ... hs) {};path.wi ... ths) {}path.win32.joinpath.wi ... ts) {};path.wi ... nts) {}path.win32.resolvepath.wi ... bsolutepath.wi ... to) {};path.wi ...  to) {}path.win32.relativepath.win32.dirnamepath.wi ... xt) {};path.wi ... ext) {}path.win32.basenamepath.win32.extnamepath.win32.sep;path.win32.seppath.wi ... imiter;path.win32.delimiterpath.win32.parsepath.wi ... pP) {};path.wi ... (pP) {}path.win32.formatmodule. ... edPath;module. ... sedPathmodule. ... malize;module. ... rmalizemodule. ... h.join;module. ... th.joinmodule.exports.joinmodule. ... solute;module. ... bsolutemodule. ... lative;module. ... elativemodule. ... irname;module. ... dirnamemodule. ... sename;module. ... asenamemodule. ... xtname;module. ... extnamemodule. ... th.sep;module. ... ath.sepmodule.exports.sepmodule. ... imiter;module. ... limitermodule. ... .parse;module. ... h.parsemodule.exports.parsemodule. ... format;module. ... .formatmodule. ... .posix;module. ... h.posixmodule.exports.posixmodule. ... .win32;module. ... h.win32module.exports.win32path._m ... th) {};path._m ... ath) {}path._makeLongmodule. ... keLong;module. ... akeLongpath.ex ... ck) {};path.ex ... ack) {}path.existspath.ex ... th) {};path.ex ... ath) {}path.existsSync/opt/codeql/javascript/tools/data/externs/nodejs/process.js
+ ParsedPathextpathSegmentsisAbsoluterelativedirnamebasenameextnamesepdelimiterpathStringpathObjectposixpPwin32_makeLongDefinitions for module "path"...stringpath.ParsedPath(function (boolean): *)function (boolean): *var path = {};path = {}path.Pa ... n() {};path.Pa ... on() {}path.Pa ... e.root;path.Pa ... pe.rootpath.Pa ... ototypepath.Pa ... pe.dir;path.Pa ... ype.dirpath.Pa ... e.base;path.Pa ... pe.basepath.Pa ... pe.ext;path.Pa ... ype.extpath.Pa ... e.name;path.Pa ... pe.namepath.no ... (p) {};path.no ... n(p) {}path.normalizefunction(p) {}path.jo ... hs) {};path.jo ... ths) {}function(paths) {}path.re ... ts) {};path.re ... nts) {}path.is ... th) {};path.is ... ath) {}path.isAbsolutepath.re ... to) {};path.re ...  to) {}path.relativefunctio ...  to) {}path.di ... (p) {};path.di ... n(p) {}path.dirnamepath.ba ... xt) {};path.ba ... ext) {}path.basenamefunction(p, ext) {}path.ex ... (p) {};path.ex ... n(p) {}path.extnamepath.sep;path.seppath.delimiter;path.delimiterpath.pa ... ng) {};path.pa ... ing) {}path.parsepath.fo ... ct) {};path.fo ... ect) {}path.formatfunctio ... ect) {}path.po ...  || {};path.po ... x || {}path.posixpath.posix || {}path.po ... (p) {};path.po ... n(p) {}path.posix.normalizepath.po ... hs) {};path.po ... ths) {}path.posix.joinpath.po ... ts) {};path.po ... nts) {}path.posix.resolvepath.po ... bsolutepath.po ... to) {};path.po ...  to) {}path.posix.relativepath.posix.dirnamepath.po ... xt) {};path.po ... ext) {}path.posix.basenamepath.posix.extnamepath.posix.sep;path.posix.seppath.po ... imiter;path.posix.delimiterpath.posix.parsepath.po ... pP) {};path.po ... (pP) {}path.posix.formatfunction(pP) {}path.wi ...  || {};path.wi ... 2 || {}path.win32path.win32 || {}path.wi ... (p) {};path.wi ... n(p) {}path.win32.normalizepath.wi ... hs) {};path.wi ... ths) {}path.win32.joinpath.wi ... ts) {};path.wi ... nts) {}path.win32.resolvepath.wi ... bsolutepath.wi ... to) {};path.wi ...  to) {}path.win32.relativepath.win32.dirnamepath.wi ... xt) {};path.wi ... ext) {}path.win32.basenamepath.win32.extnamepath.win32.sep;path.win32.seppath.wi ... imiter;path.win32.delimiterpath.win32.parsepath.wi ... pP) {};path.wi ... (pP) {}path.win32.formatmodule. ... edPath;module. ... sedPathmodule. ... malize;module. ... rmalizemodule. ... h.join;module. ... th.joinmodule.exports.joinmodule. ... solute;module. ... bsolutemodule. ... lative;module. ... elativemodule. ... irname;module. ... dirnamemodule. ... sename;module. ... asenamemodule. ... xtname;module. ... extnamemodule. ... th.sep;module. ... ath.sepmodule.exports.sepmodule. ... imiter;module. ... limitermodule. ... .parse;module. ... h.parsemodule.exports.parsemodule. ... format;module. ... .formatmodule. ... .posix;module. ... h.posixmodule.exports.posixmodule. ... .win32;module. ... h.win32module.exports.win32path._m ... th) {};path._m ... ath) {}path._makeLongmodule. ... keLong;module. ... akeLongpath.ex ... ck) {};path.ex ... ack) {}path.existspath.ex ... th) {};path.ex ... ath) {}path.existsSync/opt/codeql/javascript/tools/data/externs/nodejs/process.js
  * @externs
  * @fileoverview Definitions for module "process"
  Definitions for module "process"module. ... process/opt/codeql/javascript/tools/data/externs/nodejs/punycode.js
@@ -13297,7 +13337,4 @@ http://www.w3.org/TR/cssom-view/#dom-window-screenxhttp://www.w3.org/TR/cssom-vi
 http://www.w3.org/TR/cssom-view/#dom-mediaquerylist-removelistener
 (function (!MediaQueryList): void)function (!MediaQueryList): void!MediaQueryListhttp://www.w3.org/TR/cssom-view/#mediaquerylistlistenerhttp://www.w3.org/TR/cssom-view/#screenhttp://www.w3.org/TR/cssom-view/#dom-screen-availwidthhttp://www.w3.org/TR/cssom-view/#dom-screen-availheighthttp://www.w3.org/TR/cssom-view/#dom-screen-widthhttp://www.w3.org/TR/cssom-view/#dom-screen-heighthttp://www.w3.org/TR/cssom-view/#dom-screen-colordepthhttp://www.w3.org/TR/cssom-view/#dom-screen-pixeldepthhttp://www.w3.org/TR/cssom-view/#dom-document-elementfrompointhttp://www.w3.org/TR/cssom-view/#dom-document-caretpositionfrompointhttp://dev.w3.org/csswg/cssom-view/#dom-document-scrollingelementhttp://www.w3.org/TR/cssom-view/#caretpositionhttp://www.w3.org/TR/cssom-view/#dom-caretposition-offsetnodehttp://www.w3.org/TR/cssom-view/#dom-caretposition-offset!ClientRectListhttp://www.w3.org/TR/cssom-view/#dom-element-getclientrects!ClientRecthttp://www.w3.org/TR/cssom-view/#dom-element-getboundingclientrect(boolean|{behavior: string, block: string})=(boolean|{behavior: string, block: string}){behavior: string, block: string}blockhttp://www.w3.org/TR/cssom-view/#dom-element-scrollintoview
 http://www.w3.org/TR/cssom-view/#dom-element-scrolltophttp://www.w3.org/TR/cssom-view/#dom-element-scrolllefthttp://www.w3.org/TR/cssom-view/#dom-element-scrollwidthhttp://www.w3.org/TR/cssom-view/#dom-element-scrollheighthttp://www.w3.org/TR/cssom-view/#dom-element-clienttophttp://www.w3.org/TR/cssom-view/#dom-element-clientlefthttp://www.w3.org/TR/cssom-view/#dom-element-clientwidthhttp://www.w3.org/TR/cssom-view/#dom-element-clientheighthttp://www.w3.org/TR/cssom-view/#dom-htmlelement-offsetparenthttp://www.w3.org/TR/cssom-view/#dom-htmlelement-offsettophttp://www.w3.org/TR/cssom-view/#dom-htmlelement-offsetlefthttp://www.w3.org/TR/cssom-view/#dom-htmlelement-offsetwidthhttp://www.w3.org/TR/cssom-view/#dom-htmlelement-offsetheighthttp://www.w3.org/TR/cssom-view/#dom-range-getclientrectshttp://www.w3.org/TR/cssom-view/#dom-range-getboundingclientrecthttp://www.w3.org/TR/cssom-view/#dom-mouseevent-screenxhttp://www.w3.org/TR/cssom-view/#dom-mouseevent-screenyhttp://www.w3.org/TR/cssom-view/#dom-mouseevent-pagexhttp://www.w3.org/TR/cssom-view/#dom-mouseevent-pageyhttp://www.w3.org/TR/cssom-view/#dom-mouseevent-clientxhttp://www.w3.org/TR/cssom-view/#dom-mouseevent-clientyhttp://www.w3.org/TR/cssom-view/#dom-mouseevent-xhttp://www.w3.org/TR/cssom-view/#dom-mouseevent-yhttp://www.w3.org/TR/cssom-view/#dom-mouseevent-offsetxhttp://www.w3.org/TR/cssom-view/#dom-mouseevent-offsetyhttp://www.w3.org/TR/cssom-view/#the-clientrectlist-interface
-IArrayLike.<!ClientRect>http://www.w3.org/TR/cssom-view/#dom-clientrectlist-lengthhttp://www.w3.org/TR/cssom-view/#dom-clientrectlist-itemhttp://www.w3.org/TR/cssom-view/#the-clientrect-interfacehttp://www.w3.org/TR/cssom-view/#dom-clientrect-tophttp://www.w3.org/TR/cssom-view/#dom-clientrect-righthttp://www.w3.org/TR/cssom-view/#dom-clientrect-bottomhttp://www.w3.org/TR/cssom-view/#dom-clientrect-lefthttp://www.w3.org/TR/cssom-view/#dom-clientrect-widthhttp://www.w3.org/TR/cssom-view/#dom-clientrect-heightUnknown content '://www.w3.org/TR/css3-conditional/#CSS-interface'Unknown ... erface'http://www.w3.org/TR/cssom/#the-css.escape()-method
-DOMException {@see DOMException.INVALID_CHARACTER_ERR}TODO(nicksantos): This suppress tag probably isn't needed, and
-should be removed.Set of possible string values: 'error', 'loaded', 'loading', 'unloaded'.http://dev.w3.org/csswg/css-font-loading/#enumdef-fontfaceloadstatus{style: (string|undefined), weight: (string|undefined), stretch: (string|undefined), unicodeRange: (string|undefined), variant: (string|undefined), featureSettings: (string|undefined)}http://dev.w3.org/csswg/css-font-loading/#dictdef-fontfacedescriptors!FontFaceDescriptors=!FontFaceDescriptorshttp://dev.w3.org/csswg/css-font-loading/#font-face-constructorhttp://dev.w3.org/csswg/css-font-loading/#dom-fontface-familyhttp://dev.w3.org/csswg/css-font-loading/#dom-fontface-stylehttp://dev.w3.org/csswg/css-font-loading/#dom-fontface-weighthttp://dev.w3.org/csswg/css-font-loading/#dom-fontface-stretchhttp://dev.w3.org/csswg/css-font-loading/#dom-fontface-unicoderangehttp://dev.w3.org/csswg/css-font-loading/#dom-fontface-varianthttp://dev.w3.org/csswg/css-font-loading/#dom-fontface-featuresettingshttp://dev.w3.org/csswg/css-font-loading/#dom-fontface-status!Promise.<!FontFace>Promise.<!FontFace>!FontFacehttp://dev.w3.org/csswg/css-font-loading/#font-face-loadSet of possible string values: 'loaded', 'loading'.http://dev.w3.org/csswg/css-font-loading/#enumdef-fontfacesetloadstatushttp://dev.w3.org/csswg/css-font-loading/#FontFaceSet-interfacehttp://dev.w3.org/csswg/css-font-loading/#dom-fontfaceset-add
-http://dev.w3.org/csswg/css-font-loading/#dom-fontfaceset-Æÿ ÷  íüqþ    
+IArrayLike.<!ClientRect>http://www.w3.org/TR/cssom-view/#dom-clientrectlist-lengthhttp://www.w3.org/TR/cssom-view/#dom-clientrectlist-itemhttp://www.w3.org/TR/cssom-view/#the-clientrect-interfacehttp://www.w3.org/TR/cssom-view/#dom-clientrect-tophttp://ww÷ÿ ÷  *H'    
